"""
PDF generation service using ReportLab.
Produces an in-memory PDF bytes object — no disk writes.
"""
import io
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


# ── Brand colours ──────────────────────────────────────────────────────────────
BRAND_DARK = colors.HexColor("#0F172A")
BRAND_ACCENT = colors.HexColor("#6366F1")
BRAND_LIGHT_BG = colors.HexColor("#F1F5F9")
BRAND_MUTED = colors.HexColor("#64748B")
WHITE = colors.white


def generate_pdf(summary: str, metrics: dict, filename: str) -> bytes:
    """
    Build and return a styled PDF report as raw bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Title block ────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Normal"],
        fontSize=22,
        textColor=BRAND_DARK,
        spaceAfter=4,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=BRAND_MUTED,
        spaceAfter=2,
        fontName="Helvetica",
    )
    story.append(Paragraph("Sales Insight Report", title_style))
    story.append(
        Paragraph(
            f"Generated by Rabbitt AI  ·  {datetime.utcnow().strftime('%d %B %Y, %H:%M UTC')}",
            subtitle_style,
        )
    )
    story.append(
        Paragraph(f"Source file: <i>{filename}</i>", subtitle_style)
    )
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_ACCENT))
    story.append(Spacer(1, 0.5 * cm))

    # ── Executive Summary ──────────────────────────────────────────────────────
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Normal"],
        fontSize=13,
        textColor=BRAND_ACCENT,
        spaceBefore=10,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=BRAND_DARK,
        leading=16,
        fontName="Helvetica",
    )

    story.append(Paragraph("Executive Summary", section_style))
    story.append(Paragraph(summary, body_style))
    story.append(Spacer(1, 0.5 * cm))

    # ── Key Metrics Table ──────────────────────────────────────────────────────
    story.append(Paragraph("Key Metrics", section_style))

    metric_rows = _build_metric_rows(metrics)
    if metric_rows:
        table_data = [["Metric", "Value"]] + metric_rows
        col_widths = [10 * cm, 6 * cm]
        tbl = Table(table_data, colWidths=col_widths)
        tbl.setStyle(
            TableStyle(
                [
                    # Header
                    ("BACKGROUND", (0, 0), (-1, 0), BRAND_ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 10),
                    ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                    # Body
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 1), (-1, -1), 9),
                    ("TEXTCOLOR", (0, 1), (-1, -1), BRAND_DARK),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, BRAND_LIGHT_BG]),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(tbl)

    # ── Footer note ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_MUTED))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=BRAND_MUTED,
        spaceBefore=4,
        alignment=TA_CENTER,
    )
    story.append(
        Paragraph(
            "Confidential · Rabbitt AI Sales Insight Automator · Powered by Groq Llama 3.3",
            footer_style,
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _build_metric_rows(metrics: dict) -> list[list[str]]:
    """Convert the metrics dict into human-readable table rows."""
    rows = []

    label_map = {
        "row_count": "Total Records",
        "total_revenue": "Total Revenue",
        "avg_revenue_per_row": "Avg Revenue / Record",
        "total_units_sold": "Total Units Sold",
        "top_region": "Top Region",
        "top_region_revenue": "Top Region Revenue",
        "top_category": "Top Category",
        "cancelled_orders": "Cancelled Orders",
    }
    fmt_currency = {"total_revenue", "avg_revenue_per_row", "top_region_revenue"}

    for key, label in label_map.items():
        val = metrics.get(key)
        if val is None:
            continue
        if key in fmt_currency:
            display = f"${val:,.2f}"
        elif isinstance(val, float):
            display = f"{val:,.2f}"
        else:
            display = str(val)
        rows.append([label, display])

    # Region breakdown sub-rows
    if "region_breakdown" in metrics:
        for region, rev in metrics["region_breakdown"].items():
            rows.append([f"  Revenue — {region}", f"${rev:,.2f}"])

    # Status breakdown
    if "status_breakdown" in metrics:
        for status, count in metrics["status_breakdown"].items():
            rows.append([f"  Orders — {status}", str(count)])

    return rows
